import Link from "next/link";
import { ArrowUpRight, Check, Github, Linkedin, Mail, MoveDown, Sparkles } from "lucide-react";
import { Button } from "@/shared/components/button";
import { siteConfig } from "@/shared/config/site";
import { projects, services } from "./data";
function SectionLabel({ children }: { children: React.ReactNode }) { return <p className="eyebrow text-muted">{children}</p>; }
export function PortfolioPage() {
  return <main className="overflow-hidden">
    <nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-7 lg:px-10"><Link href="#top" className="text-sm font-bold tracking-tight">PS<span className="text-muted">.</span></Link><div className="hidden items-center gap-8 text-sm text-muted md:flex"><Link href="#work" className="hover:text-ink">Work</Link><Link href="#services" className="hover:text-ink">Services</Link><Link href="#about" className="hover:text-ink">About</Link></div><Button asChild size="sm"><a href={`mailto:${siteConfig.email}`}>Let&apos;s talk <ArrowUpRight size={14} /></a></Button></nav>
    <section id="top" className="grid-lines mx-auto max-w-7xl border-b border-line px-6 pb-20 pt-16 lg:px-10 lg:pb-28 lg:pt-28"><div className="max-w-5xl"><div className="mb-8 flex items-center gap-3 text-muted"><span className="h-2 w-2 rounded-full bg-accent" /><span className="eyebrow">Available for select projects</span></div><h1 className="display max-w-5xl text-[clamp(4rem,10vw,9.5rem)] font-semibold">Frontend that<br /><span className="text-muted">moves products</span><br />forward.</h1><div className="mt-12 flex flex-col justify-between gap-8 md:flex-row md:items-end"><p className="max-w-md text-lg leading-relaxed text-muted">I&apos;m Pawel, a senior frontend engineer and team lead helping product teams turn complex ideas into clear, reliable digital experiences.</p><div className="flex items-center gap-4"><Button asChild size="lg"><a href="#work">See selected work <MoveDown size={16} /></a></Button><a href="#about" className="text-sm font-medium underline decoration-line underline-offset-8 hover:decoration-ink">More about me</a></div></div></div></section>
    <section id="services" className="mx-auto max-w-7xl border-b border-line px-6 py-20 lg:px-10 lg:py-28"><div className="grid gap-12 lg:grid-cols-[1fr_2fr]"><div><SectionLabel>What I do</SectionLabel><h2 className="display mt-5 max-w-sm text-5xl font-semibold md:text-6xl">Good code is a product advantage.</h2></div><div className="divide-y divide-line border-y border-line">{services.map((service) => <div key={service.number} className="grid gap-4 py-7 md:grid-cols-[80px_1fr_1.3fr] md:items-start"><span className="font-mono text-sm text-muted">{service.number}</span><h3 className="text-xl font-semibold">{service.title}</h3><p className="max-w-md leading-relaxed text-muted">{service.text}</p></div>)}</div></div></section>
    <section id="work" className="mx-auto max-w-7xl px-6 py-20 lg:px-10 lg:py-28"><div className="mb-14 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><SectionLabel>Selected work</SectionLabel><h2 className="display mt-5 text-5xl font-semibold md:text-7xl">Built for real use.</h2></div><p className="max-w-xs leading-relaxed text-muted">A few examples of products, systems and experiences I&apos;ve helped shape at Synthify Labs.</p></div><div className="grid gap-5 lg:grid-cols-3">{projects.map((project) => <article key={project.title} className="group"><div className={`relative mb-6 flex aspect-[4/3] items-end overflow-hidden rounded-2xl p-6 ${project.accent === "lime" ? "bg-[#d5f15c]" : project.accent === "blue" ? "bg-[#cbdcf4]" : "bg-[#f1d8c6]"}`}><div className="absolute right-6 top-6 flex h-10 w-10 items-center justify-center rounded-full bg-white/70 transition-transform group-hover:rotate-45"><ArrowUpRight size={18} /></div><div className="relative w-full rounded-xl border border-black/10 bg-white/35 p-5 backdrop-blur-sm"><div className="mb-4 flex gap-1.5"><span className="h-2 w-2 rounded-full bg-ink/50" /><span className="h-2 w-2 rounded-full bg-ink/20" /><span className="h-2 w-2 rounded-full bg-ink/20" /></div><div className="h-20 rounded-lg bg-white/50 p-3"><div className="mb-2 h-2 w-1/2 rounded-full bg-ink/40" /><div className="h-2 w-4/5 rounded-full bg-ink/15" /><div className="mt-4 flex gap-2"><div className="h-5 w-12 rounded bg-ink/15" /><div className="h-5 w-20 rounded bg-ink/10" /></div></div></div></div><p className="eyebrow text-muted">{project.type}</p><h3 className="mt-2 text-2xl font-semibold">{project.title}</h3><p className="mt-3 leading-relaxed text-muted">{project.description}</p><div className="mt-5 flex flex-wrap gap-2">{project.tags.map((tag) => <span key={tag} className="rounded-full border border-line px-3 py-1 text-xs text-muted">{tag}</span>)}</div></article>)}</div></section>
    <section id="about" className="bg-ink text-white"><div className="mx-auto grid max-w-7xl gap-14 px-6 py-20 lg:grid-cols-[1fr_1.5fr] lg:px-10 lg:py-28"><div><SectionLabel>About me</SectionLabel><h2 className="display mt-5 text-5xl font-semibold text-white md:text-7xl">Senior enough to lead. Curious enough to keep learning.</h2></div><div className="max-w-xl lg:pt-12"><p className="text-xl leading-relaxed text-white/75">For the last five years I&apos;ve worked on production React, TypeScript and React Native applications — including a browser extension used by around 300k users.</p><p className="mt-6 leading-relaxed text-white/60">I care about the details that make software last: a thoughtful component model, accessible interaction, clear communication and a team that can confidently ship the next thing.</p><div className="mt-10 grid gap-3 text-sm sm:grid-cols-2">{["React & TypeScript", "Design systems", "Accessibility & UX", "Performance", "REST API integration", "Mentoring & leadership"].map((item) => <div key={item} className="flex items-center gap-3 text-white/80"><Check size={15} className="text-accent" />{item}</div>)}</div></div></div></section>
    <section id="contact" className="mx-auto max-w-7xl px-6 py-20 lg:px-10 lg:py-32"><div className="rounded-3xl bg-accent p-8 md:p-14 lg:p-20"><div className="flex max-w-4xl flex-col justify-between gap-12 md:flex-row md:items-end"><div><div className="mb-8 flex items-center gap-3"><Sparkles size={18} /><span className="eyebrow">Have a good problem?</span></div><h2 className="display text-5xl font-semibold md:text-8xl">Let&apos;s make it<br />useful.</h2></div><div className="max-w-xs"><p className="mb-6 leading-relaxed">Tell me what you&apos;re building, where you&apos;re stuck, or what could work better.</p><Button asChild variant="default" size="lg"><a href={`mailto:${siteConfig.email}`}>Start a conversation <ArrowUpRight size={17} /></a></Button></div></div></div></section>
    <footer className="mx-auto flex max-w-7xl flex-col gap-6 border-t border-line px-6 py-8 text-sm text-muted md:flex-row md:items-center md:justify-between lg:px-10"><p>© {new Date().getFullYear()} Pawel Szydlo</p><div className="flex items-center gap-5"><a href={siteConfig.linkedin} target="_blank" rel="noreferrer" aria-label="LinkedIn"><Linkedin size={17} /></a><a href={siteConfig.github} target="_blank" rel="noreferrer" aria-label="GitHub"><Github size={17} /></a><a href={`mailto:${siteConfig.email}`} aria-label="Email"><Mail size={17} /></a></div><p>React · TypeScript · Product thinking</p></footer>
  </main>;
}
